### ISSUE TITLE
Restart of bridge causes Relaybotted state events to be echoed back into matrix

### ISSUE THREAD

**Issue by maltee1** [mautrix/telegram#789] opened 2022-04-27 08:24 UTC
Upon bridge restart, the most recent relaybotted state events are echoed from the telegram group back into matrix (sent from the relaybot ghost). This appears to affect only those state events that were sent after the last regular message. I suspect that the marker set by the bridge to mark the most recently bridged message is not moved in the case of state events, causing the bridge to pick them up when it tries to figure out what happened in telegram while it was gone. Possibly the marker needs to be moved or the sync after restart should ignore messages by the relaybot.
To reproduce
1. bridge a room into signal and invite the relaybot
2. Have a non-logged-in user join, leave or change name in matrix.
3. restart the bridge
4. observe spam.

**Comment by tulir** [comment] 2022-09-21 19:01
Duplicate of #504

**Closed by tulir** 2022-09-21 19:01 UTC
