### ISSUE TITLE
Unhandled error while handling command: clean-rooms

### ISSUE THREAD

**Issue by Kitanit** [mautrix/telegram#868] opened 2022-11-16 07:01 UTC
![image](https://user-images.githubusercontent.com/65107731/202108351-986c0a3d-c8a9-44c2-8530-812e83383f91.png)

**Comment by tulir** [comment] 2022-12-03 12:18
Probably a duplicate of mautrix/python#33, but can't tell for sure because you forgot to include the full error message

**Closed by tulir** 2022-12-03 12:18 UTC

**Comment by Kitanit** [comment] 2022-12-03 12:29
> 

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.10/site-packages/mautrix_telegram/commands/handler.py", line 192, in _run_handler
    return await handler(evt)
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 340, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/clean_rooms.py", line 76, in clean_rooms
    results = await _find_rooms(evt.bridge)
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/clean_rooms.py", line 58, in _find_rooms
    members = await portal.get_authenticated_matrix_users()
  File "/usr/lib/python3.10/site-packages/mautrix_telegram/portal.py", line 3612, in get_authenticated_matrix_users
    members = await self.main_intent.get_room_members(self.mxid)
  File "/usr/lib/python3.10/site-packages/mautrix/appservice/api/intent.py", line 462, in get_room_members
    memberships = await self.get_joined_members(room_id)
  File "/usr/lib/python3.10/site-packages/mautrix/appservice/api/intent.py", line 141, in wrapper
    return await __method(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/mautrix/client/store_updater.py", line 196, in get_joined_members
    await self.state_store.set_members(room_id, members, only_membership=Membership.JOIN)
  File "/usr/lib/python3.10/site-packages/mautrix/client/state_store/asyncpg/store.py", line 169, in set_members
    await conn.copy_records_to_table(
  File "/usr/lib/python3.10/site-packages/mautrix/util/async_db/connection.py", line 38, in wrapper
    ret = await func(self, arg, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/mautrix/util/async_db/connection.py", line 151, in copy_records_to_table
    return await self.wrapped.copy_records_to_table(
  File "/usr/lib/python3.10/site-packages/asyncpg/connection.py", line 984, in copy_records_to_table
    return await self._protocol.copy_in(
  File "asyncpg/protocol/protocol.pyx", line 529, in copy_in
asyncpg.exceptions.UniqueViolationError: duplicate key value violates unique constraint "mx_user_profile_pkey"
DETAIL:  Key (room_id, user_id)=(!reVkqBtbbAFLhXlOmL:tech.securetown.top, @uebatortg:tech.securetown.top) already exists.

```

**Comment by Kitanit** [comment] 2022-12-03 12:31
@tulir

**Comment by tulir** [comment] 2022-12-03 12:47
Hmm, that might be something else, but it also shouldn't be possible 🤔

**Comment by Kitanit** [comment] 2022-12-04 07:19
docker
![image](https://user-images.githubusercontent.com/65107731/205479165-b8f161ac-ad50-49c4-964a-a015309841e8.png)

**Comment by Kitanit** [comment] 2022-12-04 07:20
I may have a broken database, but I can't rule it out.
