### ISSUE TITLE
Random disconnect from Android app after login

### ISSUE THREAD

**Issue by LoricAndre** [mautrix/telegram#808] opened 2022-06-23 07:35 UTC
Hello,
I've setup the bridge using matrix-ansible-deploy on an oracle arm vm without any issue whatsoever.
However, every time I login to the bridge, I get disconnected from the android telegram app after a few hours.

**Comment by tulir** [comment] 2022-06-23 07:36
Duplicate of #733, but it's probably a bug on telegram's side

**Closed by tulir** 2022-06-23 07:36 UTC
