### ISSUE TITLE
Error when using !tg sync

### ISSUE THREAD

**Issue by chagai95** [mautrix/telegram#650] opened 2021-07-31 16:45 UTC
*Telegram bridge bot*:: 
Unhandled error while handling command:

```Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1263, in _execute_context
    self.dialect.do_executemany(
  File "/usr/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 873, in do_executemany
    cursor.executemany(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "idx_147145_sqlite_autoindex_user_portal_1"
DETAIL:  Key ("user", portal, portal_receiver)=(1094837295, 1505803792, 1505803792) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 405, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/commands/handler.py", line 121, in _run_handler
    return await handler(evt)
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 290, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/commands/telegram/misc.py", line 189, in sync
    await evt.sender.sync_dialogs()
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/user.py", line 415, in sync_dialogs
    await self.save(portals=True)
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/user.py", line 170, in save
    self.db_instance.portals = self.db_portals
  File "/usr/lib/python3.8/site-packages/mautrix_telegram/db/user.py", line 83, in portals
    conn.execute(UserPortal.t.insert(), insert_portals)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1020, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1133, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1323, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1517, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1263, in _execute_context
    self.dialect.do_executemany(
  File "/usr/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 873, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "idx_147145_sqlite_autoindex_user_portal_1"
DETAIL:  Key ("user", portal, portal_receiver)=(1094837295, 1505803792, 1505803792) already exists.

[SQL: INSERT INTO user_portal ("user", portal, portal_receiver) VALUES (%(user)s, %(portal)s, %(portal_receiver)s)]
[parameters: ({'user': 1094837295, 'portal': 1468629521, 'portal_receiver': 1468629521}, {'user': 1094837295, 'portal': 1232525906, 'portal_receiver': 1232525906}, {'user': 1094837295, 'portal': 777000, 'portal_receiver': 1094837295}, {'user': 1094837295, 'portal': 1488195330, 'portal_receiver': 1488195330}, {'user': 1094837295, 'portal': 1480533390, 'portal_receiver': 1480533390}, {'user': 1094837295, 'portal': 299986122, 'portal_receiver': 1094837295}, {'user': 1094837295, 'portal': 1153809416, 'portal_receiver': 1153809416}, {'user': 1094837295, 'portal': 500777365, 'portal_receiver': 500777365}  ... displaying 10 of 178 total bound parameter sets ...  {'user': 1094837295, 'portal': 511013363, 'portal_receiver': 511013363}, {'user': 1094837295, 'portal': 1505803792, 'portal_receiver': 1505803792})]
(Background on this error at: http://sqlalche.me/e/gkpj)
```

**Comment by tulir** [comment] 2022-01-08 21:43
Duplicate of #596 and probably doesn't apply anymore

**Closed by tulir** 2022-01-08 21:43 UTC
