### ISSUE TITLE
Sending a message twice

### ISSUE THREAD

**Issue by chagai95** [mautrix/telegram#626] opened 2021-06-11 06:45 UTC
I think the telegram bridge is sending my message again, so I get it sent twice.

![image](https://user-images.githubusercontent.com/31655082/121642346-afe42d00-ca90-11eb-90af-d916d816a523.png)

Event ID for the first message:
```
{
  "type": "m.room.message",
  "sender": "@me:chagai.website",
  "content": {
    "msgtype": "m.text",
    "body": "Good morning, i haven't read all messages carefully but I did get an answer from Tanja that she can moderate and from Shawn that he also thinks it's great, not sure if Shawn is gonna join but if there are no last minute changes I think we can expect Tanja 😊"
  },
  "origin_server_ts": 1623392446497,
  "unsigned": {
    "age": 71374
  },
  "event_id": "$N6y-dPPArqnDAR7mj9p7TdqbYwBn9hcrP-L6kVf9P4g",
  "room_id": "!gGjMmeyQavLEcOoVQX:chagai.website"
}
```

for the second message:
```
{
  "type": "m.room.message",
  "sender": "@me:chagai.website",
  "content": {
    "msgtype": "m.text",
    "body": "Good morning, i haven't read all messages carefully but I did get an answer from Tanja that she can moderate and from Shawn that he also thinks it's great, not sure if Shawn is gonna join but if there are no last minute changes I think we can expect Tanja 😊",
    "external_url": "https://t.me/c/571063562/2465",
    "net.maunium.telegram.puppet": true
  },
  "origin_server_ts": 1623392447242,
  "unsigned": {
    "age": 70629
  },
  "event_id": "$mFU5CoNOoHXt0AI5bninoQlerpzEktHZMPvO3plP9WE",
  "room_id": "!gGjMmeyQavLEcOoVQX:chagai.website"
}
```

I have two accounts in one group on Telegram, one of them used to be double puppeted but is not logged in anymore.

Here is some information from the Telegram side:
The info from the main account which is now double puppeted:
![image](https://user-images.githubusercontent.com/31655082/121642529-efab1480-ca90-11eb-8025-d0480d3eb349.png)

The info from the old account which is not logged in anymore:
![image](https://user-images.githubusercontent.com/31655082/121642771-444e8f80-ca91-11eb-93ad-43be53d4e454.png)

this is both the same message! the message only shows once on Telegram!

Some bridge logs:

```
Jun 11 08:20:46 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:46,860] [DEBUG@mau.mx] Received Matrix event $N6y-dPPArqnDAR7mj9p7TdqbYwBn9hcrP-L6kVf9P4g from @me:chagai.website in !gGjMmeyQavLEcOoVQX:chagai.website
Jun 11 08:20:46 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:46,861] [INFO@aiohttp.access] 172.18.0.4 [11/Jun/2021:06:20:46 +0000] "PUT /transactions/822005?access_token=6c1958ee-d368-5645-972e-dfaa9503df17 HTTP/1.1" 200 158 "-" "Synapse/1.35.1"
Jun 11 08:20:46 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:46,861] [DEBUG@telethon.1094837295.extensions.messagepacker] Assigned msg_id = 6972417467589350744 to SendMessageRequest (7f381e372460)
Jun 11 08:20:46 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:46,861] [DEBUG@telethon.1094837295.network.mtprotosender] Encrypting 1 message(s) in 312 bytes for sending
Jun 11 08:20:46 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:46,861] [DEBUG@telethon.1094837295.network.mtprotosender] Encrypted messages put in a queue to be sent
Jun 11 08:20:46 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:46,861] [DEBUG@telethon.1094837295.network.mtprotosender] Waiting for messages to send...
Jun 11 08:20:46 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:46,862] [DEBUG@telethon.1094837295.extensions.messagepacker] Assigned msg_id = 6972417467591767356 to MsgsAck (7f381e3aa460)
Jun 11 08:20:46 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:46,862] [DEBUG@telethon.1094837295.network.mtprotosender] Encrypting 1 message(s) in 36 bytes for sending
Jun 11 08:20:46 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:46,862] [DEBUG@telethon.1094837295.network.mtprotosender] Encrypted messages put in a queue to be sent
Jun 11 08:20:46 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:46,862] [DEBUG@telethon.1094837295.network.mtprotosender] Waiting for messages to send...
Jun 11 08:20:47 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:47,050] [DEBUG@telethon.1094837295.network.mtprotosender] Handling RPC result for message 6972417467589350744
Jun 11 08:20:47 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:47,051] [DEBUG@telethon.1094837295.network.mtprotosender] Receiving items from the network...
Jun 11 08:20:47 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:47,098] [DEBUG@telethon.relaybot.network.mtprotosender] Handling gzipped data
Jun 11 08:20:47 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:47,098] [DEBUG@telethon.relaybot.network.mtprotosender] Handling update Updates
Jun 11 08:20:47 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:47,164] [DEBUG@telethon.relaybot.network.mtprotosender] Receiving items from the network...
Jun 11 08:20:47 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:47,467] [DEBUG@mau.portal.571063562] Handled telegram message 2465 -> $mFU5CoNOoHXt0AI5bninoQlerpzEktHZMPvO3plP9WE
Jun 11 08:20:47 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:47,573] [DEBUG@mau.mx] Ignoring puppet-sent event $mFU5CoNOoHXt0AI5bninoQlerpzEktHZMPvO3plP9WE
Jun 11 08:20:47 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:47,573] [INFO@aiohttp.access] 172.18.0.4 [11/Jun/2021:06:20:47 +0000] "PUT /transactions/822006?access_token=6c1958ee-d368-5645-972e-dfaa9503df17 HTTP/1.1" 200 158 "-" "Synapse/1.35.1"
Jun 11 08:20:47 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:47,601] [DEBUG@telethon.1094837295.extensions.messagepacker] Assigned msg_id = 6972417470845425296 to SetTypingRequest (7f381e34ad90)
Jun 11 08:20:47 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:47,601] [DEBUG@telethon.1094837295.network.mtprotosender] Encrypting 1 message(s) in 36 bytes for sending
Jun 11 08:20:47 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:47,602] [DEBUG@telethon.1094837295.network.mtprotosender] Encrypted messages put in a queue to be sent
Jun 11 08:20:47 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:47,602] [DEBUG@telethon.1094837295.network.mtprotosender] Waiting for messages to send...
Jun 11 08:20:47 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:47,602] [DEBUG@telethon.1094837295.extensions.messagepacker] Assigned msg_id = 6972417470847917248 to MsgsAck (7f381e3e1850)
Jun 11 08:20:47 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:47,602] [DEBUG@telethon.1094837295.network.mtprotosender] Encrypting 1 message(s) in 36 bytes for sending
Jun 11 08:20:47 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:47,602] [DEBUG@telethon.1094837295.network.mtprotosender] Encrypted messages put in a queue to be sent
Jun 11 08:20:47 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:47,602] [DEBUG@telethon.1094837295.network.mtprotosender] Waiting for messages to send...
Jun 11 08:20:47 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:47,614] [INFO@aiohttp.access] 172.18.0.4 [11/Jun/2021:06:20:47 +0000] "PUT /transactions/822007?access_token=6c1958ee-d368-5645-972e-dfaa9503df17 HTTP/1.1" 200 158 "-" "Synapse/1.35.1"
Jun 11 08:20:47 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:47,742] [DEBUG@telethon.1094837295.network.mtprotosender] Handling RPC result for message 6972417470845425296
Jun 11 08:20:47 localhost.localdomain matrix-mautrix-telegram[20165]: [2021-06-11 06:20:47,743] [DEBUG@telethon.1094837295.network.mtprotosender] Receiving items from the network...
```

**Comment by tulir** [comment] 2021-06-11 06:49
If it's a non-supergroup, duplicate of #146. Don't use non-supergroups if there are multiple users logged into the bridge (preferably don't use them at all really)

**Comment by chagai95** [comment] 2021-06-12 07:55
Thanks for answering! It's difficult to avoid using super groups, since you can only become a super group after having 200 members I think. There is only one member logged in to the bridge, the other used to be logged in, maybe I need to clean some data about that user in the DB?

**Comment by tulir** [comment] 2021-06-12 09:23
You can become a supergroups at any time. If the user using the bridge is admin, simply do `!tg upgrade`, otherwise there are certain settings the admin can toggle to make it upgrade (because telegram removed the manual upgrade button some time ago)

**Closed** 2021-12-26 13:29 UTC
