### ISSUE TITLE
Fatal error creating Matrix room: ChannelParticipantBanned' object has no attribute 'user_id'

### ISSUE THREAD

**Issue by Half-Shot** [mautrix/telegram#686] opened 2021-11-04 09:51 UTC
```
[2021-11-04 00:03:54,224] [DEBUG@telethon.140451103.network.mtprotosender] Handling RPC result for message 7026498782367261248
[2021-11-04 00:03:54,226] [DEBUG@telethon.140451103.network.mtprotosender] Receiving items from the network...
[2021-11-04 00:03:54,241] [ERROR@mau.portal.1456595899] Fatal error creating Matrix room
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal/metadata.py", line 277, in create_matrix_room
    return await self._create_matrix_room(user, entity, invites)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal/metadata.py", line 378, in _create_matrix_room
    users = await self._get_users(user, entity)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal/metadata.py", line 855, in _get_users
    return await self._get_channel_users(user, entity, limit)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal/metadata.py", line 819, in _get_channel_users
    return list(self._filter_participants(response.users, response.participants))
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal/metadata.py", line 805, in _filter_participants
    participant_map = {part.user_id: part for part in participants}
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal/metadata.py", line 805, in <dictcomp>
    participant_map = {part.user_id: part for part in participants}
AttributeError: 'ChannelParticipantBanned' object has no attribute 'user_id'
```
Seems like we're missing a check here, as presumably we should skip unprocessable members?

**Comment by tulir** [comment] 2021-11-04 09:57
Duplicate of #635

**Closed by tulir** 2021-11-04 09:57 UTC
