### ISSUE TITLE
Reply on text message with an image is not bridged

### ISSUE THREAD

**Issue by sriverg2** [mautrix/telegram#973] opened 2024-09-03 18:06 UTC
Reproduced on the latest version 0.15.2

Steps to reproduce: 
- Bridge a channel in telegram and matrix room using telegram bot and mautrix-telegram
- Send a message from telegram with an image and text 
- in matrix two messages are received: text and image separately 
- if reply in matrix on the message with the image - it's displayed in telegram as a reply on the source message
- if reply in matrix on the message with the text - it's displayed in telegram as just a separate message (not as a reply on the source message)

**Comment by tulir** [comment] 2024-09-03 18:18
Duplicate of #969

**Closed by tulir** 2024-09-03 18:18 UTC
