### ISSUE TITLE
Creating a new chat with the relay bot will cause messages to be sent via the relay bot until sync

### ISSUE THREAD

**Issue by maltee1** [mautrix/telegram#803] opened 2022-06-15 07:47 UTC
To reproduce
- create a new chat with the relay bot
- send a message
- observe the message being relayed on the telegram side
- sync or restart the bridge
- observe the message being sent by the correct user

I assume some initialization must be performed to tell the portal which users are logged in.

**Comment by tulir** [comment] 2023-01-14 11:03
Probably duplicate of #367

**Closed by tulir** 2023-01-14 11:03 UTC
