### ISSUE TITLE
Bridge only writing as bot and not puppeting

### ISSUE THREAD

**Issue by TheGeka** [mautrix/telegram#807] opened 2022-06-22 19:55 UTC
The bridge is only writing as the bot and not as myself even tho I am logged in and writing personal messages works.

**Comment by maltee1** [comment] 2022-06-23 05:40
Could this be a duplicate of https://github.com/mautrix/telegram/issues/803 ?

**Comment by TheGeka** [comment] 2022-06-23 14:22
I think so it worked after a friend used !tg sync

**Closed** 2023-01-14 10:51 UTC
