### ISSUE TITLE
When message with image is changed in Telegram, the image is lost in Matrix

### ISSUE THREAD

**Issue by Fale** [mautrix/telegram#798] opened 2022-05-28 14:56 UTC
When a message with an image is changed in Telegram, the image is lost in Matrix.

Steps:
1. From Telegram (user A) send an image
2. From Telegram (user A) edits the message and adds a caption
3. From Matrix (user B) looks at the message and will see the caption but not the image

**Comment by tulir** [comment] 2022-05-28 14:58
Duplicate of #149 

(although the image is not lost anymore, only the caption is not updated)

**Closed by tulir** 2022-05-28 14:58 UTC
